### ISSUE TITLE
Modifying Readme.md

### ISSUE THREAD

**Issue by kikislater** [Francklin2/RTKLIB_Touchscreen_GUI#18]
I have modified the readme file.

If you have suggestion, please send your message here.

**Comment by Francklin2** [comment]
Great ,it's looks better with the miage now, the mink with your precision tests on Rtklib précision gives a lot of answers  about the résults we cpuld have

**Comment by Francklin2** [comment]
I added a link to a Raspbian iso with pré-installed RTKbase (latest master) it has Qtcreator and compiler installed so it can be easyly updated

**Comment by kikislater** [comment]
Nice, so user don't need to build software itself

**Comment by kikislater** [comment]
Adding some tests results

**Comment by Francklin2** [comment]
Thank's for the test resuluts, I changed the pictures of the RTKbase (putted nices screw on it and took a real camera and not my phone ...)

**Comment by kikislater** [comment]
Nice ! Not so much time at this moment, but I could be able to test it on a drone ...
