### ISSUE TITLE
Create simple script to build RTKBASE

### ISSUE THREAD

**Issue by kikislater** [Francklin2/RTKLIB_Touchscreen_GUI#2]
RTKBASE is built with several command like : 
- Build static rtklib (there is a file problem : it's not executable => don't know if I could change the rights of this file under github)
- Then building RTKBASE

It's more simple to add one command to do that like run_build.sh or other name. Script below : 

_

> # !/bin/bash
> 
> cd lib/rtklib
> chmod +x make_library.sh
> sh make_library.sh
> cd ../../
> make clean
> qmake
> make

_

**Comment by Francklin2** [comment]
Thanks for the script, it solve the rights mistake in the files (I tried to update the rights before uploading with chown  pi:pi -R /home/pi/RTKBASE but i'm not sure if the rights are still good after transfering from the raspberry to desktop pc and uploading here, so this script is a good solution to prevent files rights issues

**Comment by kikislater** [comment]
Rights problems are on make_library.sh under rtklib not on RTKBASE :)

**Comment by kikislater** [comment]
So script solve, just need to modify wiki. I'll do
