### ISSUE TITLE
Add a custom splash screen at boot

### ISSUE THREAD

**Issue by Francklin2** [Francklin2/RTKLIB_Touchscreen_GUI#20]
On my Raspbian image I add a custom splash screen and removed boot messages,it works but I'm not sure it's the best method to do this. Here is what I did:
- Install fbi with sudo apt-get install fbi
- Add splash image to etc folder (splash.png)
  -Create a asplashscreen file in etc/init.d/asplashscreen and put the script found in this tuto:
  http://www.raspberry-projects.com/pi/pi-operating-systems/raspbian/custom-boot-up-screen
- Make the script executable and install it for init mode:
  sudo chmod a+x /etc/init.d/asplashscreen
  sudo insserv /etc/init.d/asplashscreen
- Edit /boot/cmdline.txt to remove text message and add loglevel=3 at the end of file and change console=tty1 to console=tty3

**Comment by kikislater** [comment]
Splash screen on boot when Raspian is loading ?

**Comment by Francklin2** [comment]
Yes it was the idea,I dont know if it was the best way to do it

**Comment by kikislater** [comment]
I don't know raspberry pi system but seems to be good

**Comment by Francklin2** [comment]
It will be more easy for you to see that when you will have you raspberry, it's working well for the moment so I  upload the splash image in the IMG folder and I wil add the instruction for splash screen in the wiki and readme.md
Perhaps it will be better to create a separate folder in root for splash screen files ?

**Comment by Francklin2** [comment]
I put all files for splashscreen in a separate folder with a install manual
