### ISSUE TITLE
Set Raspberry pi Time and date with GNSS clock

### ISSUE THREAD

**Issue by Francklin2** [Francklin2/RTKLIB_Touchscreen_GUI#22]
Is it possible to set Raspberry pi clock with the GNSS clock ? it"s done after boot with internet clock if internet connexion is avalaible

**Comment by kikislater** [comment]
Otherwise the clock is set to which setting ?

**Comment by Francklin2** [comment]
It goes back to 2008 or a default date like this

**Comment by kikislater** [comment]
Ok I understand, I have the same problem. I have to check when I have time

**Comment by Francklin2** [comment]
I made a setting button in solution status windows in the Beta version to set system time with GPS time, only in UTC time for now

**Comment by Francklin2** [comment]
seemed to work nice now so i can close the issue. 
There could be a second delay  in the  clock setup but it should be good to avoid date file issues
