### ISSUE TITLE
duplicate 'install' in apt-get command in build script

### ISSUE THREAD

**Issue by benreh** [Francklin2/RTKLIB_Touchscreen_GUI#25]
Your line has a duplicate "install" in the apt-get command:

`sudo apt-get install --assume-yes libxtst-dev build-essential libqt4-dev qt4-qmake libqt4-core libqt4-gui --->install<--- libqt4-xml libqt4`

I would also suggest to add a  `set -e` at the beginning of the shell script so it aborts if a command fails.
It is more obvious then, that somethings went wrong.

Thanks!

**Comment by kikislater** [comment]
Done. 
Thank you 

https://github.com/Francklin2/RTKLIB_Touchscreen_GUI/commit/a8512eb2c2343b48f7ad967dfd5775323735a8af
