### ISSUE TITLE
Can not use RTK-Kinematic

### ISSUE THREAD

**Issue by QUOCHUY1325** [Francklin2/RTKLIB_Touchscreen_GUI#26]
I can't use RTK Kinematic in Rover (but i can use Single and DGPS), when i choose Status, Sat Rover Number don't show anythung  although Sat Base Number is counting. 
Please, can you check my code  ? 

# rtkrcv options (2010/08/12 07:12:16, v.2.4.0) 
console-passwd	=admin
console-timetype  =utc		# (0:gpst,1:utc,2:jst,3:tow)
 console-soltype	=deg		# (0:dms,1:deg,2:xyz,3:enu,4:pyl) 
console-solflag	=1	# (0:off,1:std+2:age/ratio/ns)
inpstr1-type =serial #(0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,7:ntripcli,8:ftp,9:http)
inpstr2-type =serial #(0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,7:ntripcli,8:ftp,9:http)
inpstr3-type  =	off	# (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,7:ntripcli,8:ftp,9:http)
inpstr1-path	=ttyACM0:115200:8:n:1:off
 inpstr2-path	=ttyUSB0:115200:8:n:1:off
inpstr3-path	=
inpstr1-format	=ubx	# (0:rtcm2,1:rtcm3,2:oem4,3:oem3,4:ubx,5:ss2,6:hemis,7:skytraq,14:sp3)
inpstr2-format	=ubx	# (0:rtcm2,1:rtcm3,2:oem4,3:oem3,4:ubx,5:ss2,6:hemis,7:skytraq,14:sp3)
inpstr3-format	=	#
(0:rtcm2,1:rtcm3,2:oem4,3:oem3,4:ubx,5:ss2,6:hemis,7:skytraq,14:sp3) 
inpstr2-nmeareq	=off	# (0:off,1:latlon,2:single)
inpstr2-nmealat	=0	# (deg)
 inpstr2-nmealon		=0		# (deg)
outstr1-type	=file	# (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,6:ntripsvr)
 outstr2-type			=	#serial	# (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,6:ntripsvr)
outstr1-path	=/home/pi/RTK/solution/ppp-sol_%Y%m%d%h%M.pos 
outstr2-path	=	#ttyAMA0:115200:8:e:1:off
outstr1-format	=llh	# (0:llh,1:xyz,2:enu,3:nmea) 
outstr2-format	=llh	# (0:llh,1:xyz,2:enu,3:nmea)
logstr1-type =file # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,6:ntripsvr) 
logstr2-type =file # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,6:ntripsvr) 
logstr3-type =file # (0:off,1:serial,2:file,3:tcpsvr,4:tcpcli,6:ntripsvr) 
logstr1-path      =/home/pi/RTK/solution/rov_%Y%m%d%h%M.log
logstr2-path =/home/pi/RTK/solution/ref_%Y%m%d%h%M.log 
logstr3-path =/home/pi/RTK/solution/cor_%Y%m%d%h%M.log 
misc-svrcycle      =10         # (ms)
misc-timeout		=30000		# (ms) 
misc-reconnect        =30000			# (ms) 
misc-nmeacycle	=5000			# (ms) 
misc-buffsize	=32768	# (bytes)
misc-navmsgsel		=rover	# (0:all,1:rover,1:base,2:corr) 
misc-startcmd	=/home/pi/RTK/startscripts/rtkstart.sh 
misc-stopcmd	=/home/pi/RTK/startscripts/rtkshut.sh
file-cmdfile1=/home/pi/RTK/startscripts/ubx_m8t_raw_1hz.cmd 
file-cmdfile2	=
file-cmdfile3	=
pos1-posmode=kinematic
#(0:single,1:dgps,2:kinematic,3:static,4:movingbase,5:fixed,6:ppp-kine,7:ppp- static)
pos1-frequency	=l1	# (1:l1,2:l1+l2,3:l1+l2+l5)
pos1-soltype	=forward		# (0:forward,1:backward,2:combined) 
pos1-elmask		=15	# (deg)
pos1-snrmask		=off			# (dBHz) 
pos1-dynamics	=off		# (0:off,1:on) 
pos1-tidecorr	=off	# (0:off,1:on)
pos1-ionoopt	=brdc		# (0:off,1:brdc,2:sbas,3:dual-freq,4:est-stec) 
pos1-tropopt	=saas	# (0:off,1:saas,2:sbas,3:est-ztd,4:est-ztdgrad)
pos1-sateph	=brdc	# (0:brdc,1:precise,2:brdc+sbas,3:brdc+ssrapc,4:brdc+ssrcom)
.....
Don't change.

**Comment by Francklin2** [comment]
Hello
How do you plug the GNSS on the rover  side ? If it's on the serial port of the GPIO you have to use ACM0, if it's on the USB hub it will be a USB0 or USB1. Check also if the bitrate of 115200 is correct on the rover GNSS
