### ISSUE TITLE
Trying to install RTKLIB 2.4.3 but having trouble rebuilding RTKBASE

### ISSUE THREAD

**Issue by Matera87** [Francklin2/RTKLIB_Touchscreen_GUI#27]
Hi!

Great work with this GUI so far! 

I'm using the pre-installed image of RTKBASE and I have tried to upgrade the RTKLIB to latest beta version by replacing the content in the /lib/rtklib/src folder and rebuilding RTKBASE. However, I run into trouble since the current rtkrcv.c in RTKBASE folder is not compatible with the new RTKLIB version.

Is it possible to make it work?

thank you for your answer!

**Comment by Francklin2** [comment]
Try to run the build script make_library.sh in the lib folder before running the rtkbase build script
