### ISSUE TITLE
sorry, unimplemented: non-static data member initalizer

### ISSUE THREAD

**Issue by vivekyuvan** [Francklin2/RTKLIB_Touchscreen_GUI#28]
/home/akas13/Desktop/RTKLIB_Touchscreen_GUI-master/RTKBASE/MainthreadStr2str.h:26: error: ISO C++ forbids in-class initialization of non-const static member 'm_choix'

**Comment by Francklin2** [comment]
Hi you tried to compile on a desktop pc ?
