### ISSUE TITLE
RTKBASE does not finish building

### ISSUE THREAD

**Issue by Eliandthepai** [Francklin2/RTKLIB_Touchscreen_GUI#29]
I am running Linux 8.0 (jessie) on RPi 3 and I ran into an issue where the RTKBASE does not finish building. I followed the instructions on:
https://github.com/Francklin2/RTKLIB_Touchscreen_GUI/wiki/1---Installation
Followed the part Installation on Raspberry Pi 3 
It exits/crash at the ./build_rtkbase.sh when its building the RTKBASE
![img_5754](https://user-images.githubusercontent.com/21327064/29956238-ad0bfbfc-8eb3-11e7-8dbe-61b4361694bf.JPG)

I super appreciate any help I can get on this. Thank you.

**Comment by kikislater** [comment]
There is problem with latest uploaded push. It's about moving from rtklib 2.4.2 to 2.4.3
Hope Francklin will help ...

**Comment by kikislater** [comment]
According to this commit https://github.com/Francklin2/RTKLIB_Touchscreen_GUI/commit/9e7026ff6cf63ebf89efc1738aa9b05f83d977ce

I updated build script. Try it please

**Comment by Francklin2** [comment]
Yes on the Raspberry PI 3 with Raspbian Jessie , I had to run manually the library install, like this so the updated build script should work
sudo apt-get install --assume-yes libxtst-dev build-essential libqt4-dev qt4-qmake libqt4-core libqt4-gui  libqt4-xml libqt4-opengl 

I have to test it with a clean raspbian jessie on the Pi 3 too

**Comment by Francklin2** [comment]
I tryed with thr new build script on a clean raspbian Jessie and it works well getting the needed library and I get a ./RTKBASE file .
I put the build logs if you want to check , I open a new issue for the 2.4.3 errors on build 
[logs.zip](https://github.com/Francklin2/RTKLIB_Touchscreen_GUI/files/1272526/logs.zip)

**Comment by Francklin2** [comment]
The new script build well on Pi 3 so we can close this issue
