### ISSUE TITLE
Fichiers de confs nommés ubx

### ISSUE THREAD

**Issue by kikislater** [Francklin2/RTKLIB_Touchscreen_GUI#44]
Francklin,

J'ai renommé les fichiers présents dans le répertoire ConfFiles qui étaient tous nommés .ubx en .conf. : plus approprié ! 
Tu peux vérifier si ça n'impacte pas le fonctionnement. Auquel cas il faudra modifier les autres fichiers mais pas revenir en arrière sur le nommage des fichiers de conf.

A+

**Comment by Francklin2** [comment]
Salut  
Effectivement c'était une source d'erreur pour se retrouver dans les fichiers, les fichiers choixedite.cpp et choixconfig.cpp ont été adaptés pour les nouvelles extenssion en .conf

A+
