### ISSUE TITLE
Test in RPI ZERO W

### ISSUE THREAD

**Issue by messplay** [Francklin2/RTKLIB_Touchscreen_GUI#48]
Well let me share that the first test compile was "sucessfull" but ./RTKLIB is missing I am running a second compile to view if the file appear. In the other hand I compile in ubuntu and was 100% sucessfull. So if someone have some recomendation it will be welcome

**Comment by Francklin2** [comment]
Hello
Thank you for the feedback on the RPI zeroW, did you try the 2.43 branch? ( git clone https://github.com/Francklin2/RTKLIB_Touchscreen_GUI.git --branch RTKbase-2.4.3  )
I just updated it with a missing dependencie for post processing (gfortran)

**Comment by messplay** [comment]
@Francklin2  I going to test right now, let me check in my last try Zero freeze =(  let me trying again with new branch

**Comment by messplay** [comment]
Well in the last try RPI zero take 6 hours to compile. Now I still waiting.

**Comment by messplay** [comment]
Hi people well build proccess finish. Again was "sucessful" however ./RTKLIB is missing again. attached log file for reference. I saw 1 error in log.
[RTKBASE.log](https://github.com/Francklin2/RTKLIB_Touchscreen_GUI/files/3059402/RTKBASE.log)

**Comment by messplay** [comment]
Well finally build sucesfull and run in RPI zero. Virtual memory exhausted was the clue. Solved. Just need Add a Swap File to run.

**Comment by kikislater** [comment]
@Francklin2 it should be the same for you and why you need to run the script twice !

**Comment by Francklin2** [comment]
Nice to hear you find the trick for the pi zero and the lack of memory, there is still a lot of errors from qt4 to qt5 change (ISO 90 error)and also when I updated to 2.43b31(errors in vt.c, rtkrcv andstr2str and rnx2rtkp). We saw a problem  while updating the files when I do the commit, the .pro file was not updated last time (perhaps some other), I will check the file version this evening.

**Comment by messplay** [comment]
hi. tks, fine next step is test with m8p-0 in few days will arrive zed f9 ublox chip. Upload log file for reference.
[RTKBASE.log](https://github.com/Francklin2/RTKLIB_Touchscreen_GUI/files/3060765/RTKBASE.log)

**Comment by messplay** [comment]
.rover mode tested without any problem
