### ISSUE TITLE
UBX file

### ISSUE THREAD

**Issue by messplay** [Francklin2/RTKLIB_Touchscreen_GUI#56]
Hi people, I want to know if is possible store the ubx file the base and rover in the PI it would be usefull when RTK mode is not available.

**Comment by Francklin2** [comment]
Hello you have to use the base mode or the post processing mode to record UBX file.
In the base mode, in the output setting , you have to choose File instead of RTCM
In post processing,  set capture mode to let enough time before get a internet connexion and  start the automatic post processing
