### ISSUE TITLE
3.5 inch window overscreen in RTKLIB

### ISSUE THREAD

**Issue by comedoo** [Francklin2/RTKLIB_Touchscreen_GUI#57]
the driver installer ok, but de window screen of  RTKLib still overscreen ...., Am I missing something?
Thank you !!!

_Originally posted by @comedoo in https://github.com/Francklin2/RTKLIB_Touchscreen_GUI/issues/53#issuecomment-511441926_

**Comment by Francklin2** [comment]
Hello
The RtKlib interface was made for a 800x600 résolution, is it the setting in your 3.5inch screen ?

**Comment by comedoo** [comment]
my resolution is setting for 480x320, so how can I work with this resolution without overscreen ? Is possible to create another version for 3.5 inch ?
thank you !!!

**Comment by kikislater** [comment]
You need to modify configuration files. Note that the project has moved to python here : 
https://github.com/Francklin2/EasyGNSS
