### ISSUE TITLE
No GPS Data in RTKLIB

### ISSUE THREAD

**Issue by Stolponese** [Francklin2/RTKLIB_Touchscreen_GUI#58]
I Installed everything accordingly to the instruction, but the program is not able to use the data provided by the antenna. I can see that the program is communicating with the antenna, but I don't get any position-data.
With Minicom/ cgps/ gpsmon I get good data, so the chip is working. 

Any Advice?

**Comment by Francklin2** [comment]
Hello
If you have a Ublox device, did you enable the RAWX and SFRBX data ? 
https://github.com/Francklin2/RTKLIB_Touchscreen_GUI/wiki/6-Setting-the-Ublox-M8T-for-RAW

**Comment by Stolponese** [comment]
now its working! 
I have a different Chip from Ublox and didn't pay attention to the chapter. Thank you so much!
